---
title: "City_Deal_2"
author: "Lekan Ali"
date: "2024-07-16"
output: pdf_document
---

Loading data libraries
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE)
library(formatR)
library(gplots)
library(tidyverse)
library(readxl)# to read excel files
library(HH)
library(effects)
library(randomForest)
library(rlang) # to create a function for ggplot
```

### Load Datasets


```{r dataset, cache=TRUE}
# read in demographic dataset
df_demographic <- read_excel("Demographic.xlsx")

# read in activities dataset
df_activities <- read_excel("Activities.xlsx")

# read in outcome dataset
df_outcomes <- read_excel("Outcomes.xlsx")
```

## Data Exploration Section (Codes and Plots)

```{r unique clients and dataset name, echo=FALSE}
# 1.1 All three datasets have a common feature name (which is the ID of the client) but apparently this is named 'Unique ID' in the demographic and outcomes dataset and named 'ClientRef' in the Activities dataset. Hence we need to rename 'ClientRef' to 'Unique ID' so that it matches with the same name in the Demographic and outcomes sheet

names(df_activities)[1] <- "Unique ID"

# 1.2 create a function that picks only unique client and then add the name of the dataset to the final table
number_of_clients <- function(df, group, dataset) {
  df %>% group_by({{group}}) %>% 
    mutate(instances = row_number()) %>% # this code assigns a number to each instance or if a client exists 5 times in the datasets, each client will be given a number from 1 to 5
    filter(instances == 1) %>% # this picks only the first instance such that duplicates are excluded
    #dplyr::select({{group}}) %>% 
    mutate(dataset = {{dataset}}) %>% 
    dplyr::select({{group}}, dataset) # create a new column, the new column should have the name of the dataset
}

# 1.3 Demographic clients (unique clients)
df_demographic_clients <- number_of_clients(df_demographic,`Unique ID`,"Demographic")

# 1.4 Activities clients (unique clients)
df_activities_clients <- number_of_clients(df_activities,`Unique ID`, "Activities")


# 1.5 Outcomes clients (unique clients)
df_outcomes_clients <- number_of_clients(df_outcomes,`Unique ID`, "Outcomes")
```


```{r merged datasets}
# 2.1 combine the three tables such that they are ontop of each other
client_id_and_dataset <- rbind(df_demographic_clients
                               , df_activities_clients
                               , df_outcomes_clients)


# 2.2 change to factors
client_id_and_dataset$dataset <- factor(client_id_and_dataset$dataset
                                        , levels = c("Demographic"
                                                     , "Activities"
                                                     , "Outcomes"))

# 3.1 count the number of clients in each dataset
clients_per_dataset <- client_id_and_dataset %>% 
  group_by(dataset) %>% 
  summarise(count = n())
```





```{r plot of clients per dataset, fig.width=8, fig.height=6}
# 4 plot the number of client in each dataset
clients_per_dataset %>% 
  ggplot(aes(fct_rev(dataset), count)) +
  geom_col(fill = "grey70") + 
  geom_col(data = clients_per_dataset %>% filter(dataset == "Demographic")
           , fill = "#FF9999") + 
  coord_flip() +
  geom_text(data = clients_per_dataset %>% 
              filter(count > 5000), aes(label = scales::comma(count), hjust = 1.1)) +
  geom_text(data = clients_per_dataset %>% 
              filter(count < 5000), aes(label = scales::comma(count), hjust = -0.1)) +
  theme(panel.grid.major.y = element_blank()
        , panel.grid.minor.x = element_blank()
        , panel.grid.major.x = element_line(linetype = 2, color = "black", linewidth = 0.1)
        , axis.text = element_text(size = 12)) + 
  
  # add a thousand separator to the values in the x axis
  scale_y_continuous(expand = c(0,100)
                     , labels = scales::comma) + 
  
  # label only the y axis (since the plot is rotated, y axis is now x axis)
  labs(y = "number of clients in each dataset"
       , x = "") 
```



```{r, Age distribution, fig.width = 9, fig.height = 6}
## Demographic Data Exploration ###
df_demographic_unique <- df_demographic %>% 
  group_by(`Unique ID`) %>% 
  mutate(instances = row_number()) %>% 
  filter(instances == 1)


# explore age distribution
ggplot(df_demographic_unique, aes(Age)) +
  geom_histogram(binwidth = 1, color = "white") +
  scale_x_continuous(breaks = c(0, 20, 40, 60, 80, 100, 120)) +
  theme(panel.grid.minor.x = element_blank()
        , panel.grid.minor.y = element_blank()
        , panel.grid.major = element_line(linetype = 2, color = "black"
                                          , linewidth = 0.08)
        , axis.text = element_text(size = 12)
        , plot.caption = element_text(size=12, hjust=1, color="black", family = "mono")) +
  labs(y = "", caption = "Source: Demographic dataset") +
  annotate("text", x = 35, y = 450, label = "18 years Old", family = "mono") +
  annotate("segment", x = 26, xend = 19, y = 450, yend = 450,
           colour = "#FF9999", size = 1, arrow = arrow(length = unit(0.2, "inches")))
```




```{r Age distribution by sex, fig.height=6, fig.width = 8}
# explore age distribution by sex
# change sex from character column to a factor column
df_demographic_unique$Sex <- factor(df_demographic_unique$Sex
                                        , levels = c("Male", "Female", "Other Gender"
                                                     , "Prefer not to say", "Transgender"
                                                     , "Unknown"))

# plot age distribution using box plot
ggplot(df_demographic_unique, aes(Age, Sex)) +
  geom_boxplot() +
  coord_flip() +
  theme(panel.grid.minor.x = element_blank()
        , panel.grid.minor.y = element_blank()
        , panel.grid.major = element_line(linetype = 2, color = "black"
                                          , linewidth = 0.08)
        , axis.text = element_text(size = 12)
        , plot.caption = element_text(size=12, hjust=1, color="black", family = "mono")) +
  annotate("text", x = 46, y = 2.8, label = "Average (median)", family = "mono") +
  annotate("segment", x = 44, xend = 34, y = 2.4, yend = 2,
           colour = "#FF9999", size = 1, arrow = arrow(length = unit(0.2, "inches"))) +
  labs(y = "", caption = "Source: Demographic dataset")
```
```{r, echo=FALSE}
df_activities %>% 
  dplyr::select("Unique ID", nvhActivityGroupName
                , ClientActivityID
                , BeneficiaryHours, 
                ClientBeneficiaryHours) %>% 
  group_by(ClientActivityID) %>% 
  mutate(flag = row_number()) %>% 
  filter(flag == 1)
  
```


```{r, count of activities, fig.height=8, fig.width = 12}
## -- data processing for activity duration -- #

df_time_duration <- df_activities %>% 
  
  # select only needed features or columns
  dplyr::select("Unique ID", nvhActivityGroupName
                , ActivityName
                , ClientActivityID
                , BeneficiaryHours, 
                ClientBeneficiaryHours) %>% 
  group_by(ClientActivityID) %>% 
  
  # due to duplicates, we need to assign a number to each occurrence
  mutate(flag = row_number()) %>% 
  
  # select only the first instance (removes duplicates)
  filter(flag == 1) %>% 
  
  # ungroup
  ungroup()


# renaming entry
df_time_duration$nvhActivityGroupName[
  df_time_duration$nvhActivityGroupName == "Finanical/Debt"] <- "Financial/Debt"


# remove activity GROUPS that are dependent on the output (Employed)
df_time_duration_2 <- df_time_duration %>% 
  filter(nvhActivityGroupName != "Outcomes"
         , nvhActivityGroupName != "Sustainment")



# remove activity NAMES that are dependent on the output (Employed)
df_time_duration_3 <- df_time_duration_2 %>% 
  filter(ActivityName != "Vacancy application - Successful"
         , ActivityName != "Vacancy application - Unsuccessful"
         , ActivityName != "Move to Stage 5")


# -- get the total beneficiary and client beneficiary hours for each group and visualize -- #


# group by Activity group
df_grouped_by_activitygroup <- df_time_duration_3 %>%  
  group_by(nvhActivityGroupName) %>% 
  
  # this will count the total number of times each activity was done 
  summarise(count_of_activities = n() 
            , average_beneficiary_hours = mean(BeneficiaryHours)
            , average_client_hours = mean(ClientBeneficiaryHours)
            , total_beneficiary_hours = sum(BeneficiaryHours)
            , total_client_hours = sum(ClientBeneficiaryHours))


# pivot longer for facet plot purposes
df_grouped_by_activitygroup_2 <- pivot_longer(df_grouped_by_activitygroup
             , cols = c("count_of_activities"
                        , "average_beneficiary_hours"
                        , "average_client_hours")
             , names_to = "metrics") %>% 
  dplyr::select(nvhActivityGroupName, metrics, value) # select only the needed columns


# make the metrics column a factor instead of character
df_grouped_by_activitygroup_2$metrics <- factor(df_grouped_by_activitygroup_2$metrics
                                                , levels = c("count_of_activities"
                                                             , "average_beneficiary_hours"
                                                             , "average_client_hours"))



# -- create a function to visualize facet plot -- #
make_facet_plot <- function(df, col1, col2, col3) {
  # create aesthetic
  ggplot(data = df
               , aes(x = reorder( {{ col1 }}, 
                                  {{ col2 }} )
                     , y = {{ col2 }})) +
    geom_col(fill = "grey70") + # add plot type 
    theme(panel.grid = element_blank()
          , panel.grid.major.x = element_line(linetype = 2
                                              , linewidth = 0.09)
          , axis.text = element_text(size = 11)
          , strip.text = element_text(size = 10, face = "bold")) +
    labs(x = "") +
    coord_flip() + # flip plot
    facet_wrap(enquo(col3), scales = 'free_x') # add facet wrap
  
}


# --  visualizing plot -- #
make_facet_plot(df_grouped_by_activitygroup_2, nvhActivityGroupName, value, metrics) +
   # ---- highlight important metrics ----- #
  
    # highlighting the only Contact bar in the contact plot
  geom_col(data = df_grouped_by_activitygroup_2 %>% 
             filter(nvhActivityGroupName == "Contact", value > 3000 
                    | metrics == "count_of_activities")
           , aes(fill = "#FF9999")) +
  
  # highlighting bar greater than 1.9 value in the average_beneficiary_hours plots
  geom_col(data = df_grouped_by_activitygroup_2 %>% 
             filter(metrics == "average_beneficiary_hours", value > 1.9)
           , aes(fill = "#FF9999")) +
  
  # highlighting bar greater than 1.9 value in the average_beneficiary_hours plots
  geom_col(data = df_grouped_by_activitygroup_2 %>% 
             filter(metrics == "average_client_hours", value > 1.5)
           , aes(fill = "#FF9999")) +
  
  # ---- add text or values in the count_of_activities_plot ---- #
  
      # adding text to the plot for only the contact bar in the count_of_activities_plot
  geom_text(data =df_grouped_by_activitygroup_2 %>% 
              filter(nvhActivityGroupName == "Contact" 
                     , metrics == "count_of_activities")
            , aes(label = scales::comma(value), hjust = 1.1)) +
      # adding text to the plot for other activity groups in the count_of_activities_plot
  geom_text(data =df_grouped_by_activitygroup_2 %>% 
              filter(nvhActivityGroupName != "Contact" 
                     , metrics == "count_of_activities")
            , aes(label = scales::comma(value), hjust = -0.1)) +
  
  # ---- add text or values in the average beneficiaries hours plot ---- #
  
    # adding text to the plot for high value activities (values inside the bar)
  geom_text(data =df_grouped_by_activitygroup_2 %>% 
              filter(nvhActivityGroupName == "Training" 
                     | nvhActivityGroupName == "Job Related" 
                     | nvhActivityGroupName == "Job search and job matching"
                     , metrics == "average_beneficiary_hours")
            , aes(label = scales::comma(value), hjust = 1.1)) +
    # adding text to the plot for low value activity group (values outside the bar)
  geom_text(data =df_grouped_by_activitygroup_2 %>% 
              filter(nvhActivityGroupName != "Training" 
                     , nvhActivityGroupName != "Job Related" 
                     , nvhActivityGroupName != "Job search and job matching"
                     , metrics == "average_beneficiary_hours")
            , aes(label = round(value,2), hjust = -0.1)) +
  
  # ---- add text or values in the average client hours ---- #
  geom_text(data =df_grouped_by_activitygroup_2 %>% 
              filter(nvhActivityGroupName == "Job search and job matching"
                     , metrics == "average_client_hours")
            , aes(label = round(value,2), hjust = 1.1)) +
  
  geom_text(data =df_grouped_by_activitygroup_2 %>% 
              filter(nvhActivityGroupName != "Job search and job matching"
                     , metrics == "average_client_hours")
            , aes(label = round(value,2)
                  , hjust = -0.1)) +
  theme(legend.position = "none"
        , plot.caption = element_text(size=12, hjust=1, color="black"
                                      , family = "mono")) +
  labs(y = "", caption = "Source: Activities dataset") +
  scale_y_continuous(labels = scales::comma)
```






```{r, outcomes by clients, cache=TRUE, fig.width=9}
## Exploring Outcomes

df_outcomes_unique <- df_outcomes %>% 
  group_by(`Unique ID`) %>% 
  mutate(instances = row_number()) %>% 
  filter(instances == 1)


df_positive_outcomes <- df_outcomes_unique %>% 
  mutate("Subsidy start date" = case_when(`Subsidy start date` == "NULL" ~ 0
                                          , TRUE ~ 1)
         , "Subsidy end date" = case_when(`Subsidy end date` == "NULL" ~ 0
                                          , TRUE ~ 1)
         , "Employment start date" = case_when(`Employment start date` == "NULL" ~ 0
                                               , TRUE ~ 1)
         , "Self-employment start date" = case_when(`Self-employment start date` == "NULL" ~ 0
                                                    , TRUE ~ 1)
         , "Modern Apprenticeship start date" = case_when(`Modern Apprenticeship start date` == "NULL" ~ 0
                                                          , TRUE ~ 1)
         , "Work experience start date" = case_when(`Work experience start date` == "NULL" ~ 0
                                                    , TRUE ~ 1)
         , "Work experience completion date" = case_when(`Work experience completion date` == "NULL" ~ 0
                                                         , TRUE ~ 1)
         , "Volunteering start date" = case_when(`Volunteering start date` == "NULL" ~ 0
                                                 , TRUE ~ 1)
         , "Volunteering completion date" = case_when(`Volunteering completion date` == "NULL" ~ 0
                                                      , TRUE ~ 1)
         , "LTU Accredited Training start date" = case_when(`LTU Accredited Training start date` == "NULL" ~ 0
                                                            , TRUE ~ 1)
         , "Date Accredited Training qualification achieved (all participants)" = case_when(`Date Accredited Training qualification achieved (all participants)` == "NULL" ~ 0
                                                                                            , TRUE ~ 1)
         , "Further / Higher Education start date" = case_when(`Further / Higher Education start date` == "NULL" ~ 0
                                                               , TRUE ~ 1)
         , "Further / Higher Education completion date" = case_when(`Further / Higher Education completion date` == "NULL" ~ 0
                                                                    , TRUE ~ 1)
         , "Date FE/HE qualification achieved" = case_when(`Date FE/HE qualification achieved` == "NULL" ~ 0
                                                           , TRUE ~ 1)
         , "School start date" = case_when(`School start date` == "NULL" ~ 0
                                           , TRUE ~ 1))


# select specific columns (that can be regarded as positive outcomes)
df_positive_outcomes_1 <- df_positive_outcomes %>% 
  dplyr::select(
    1, 3, 5, 6, 7, 40, 42, 44, 48, 56)

# using pivot longer, transpose df_positive_outcomes_1 such that we have lesser columns
df_positive_outcomes_pivoted <- df_positive_outcomes_1 %>% 
  
  # transpose all columns except the first feature
  pivot_longer(cols = -1, names_to = "outcomes") 
  
# create a new column, add group the outcomes into three different groups of - 
# - Education/training, employment and others  
df_positive_outcomes_grouped <- df_positive_outcomes_pivoted %>% 
  mutate(Outcome_type = case_when(outcomes == "Subsidy start date" 
                                  | outcomes == "Subsidy end date" 
                                  | outcomes == "Work experience start date" 
                                  | outcomes == "Work experience completion date" 
                                  | outcomes == "Volunteering start date" 
                                  | outcomes == "Volunteering completion date" ~ "Others"
                                  , outcomes == "Employment start date"  
                                  |  outcomes == "Self-employment start date" 
                                  | outcomes == "Modern Apprenticeship start date" ~ "Employment"
                                  , TRUE ~ "Education & Training")) 
  

# sum each outcomes
df_positive_outcomes_grouped_sumed <- df_positive_outcomes_grouped %>% 
  group_by(outcomes, Outcome_type) %>% 
  summarise(total_outcome = sum(value))




# create a facet plot 
df_positive_outcomes_grouped_sumed %>% 
  ggplot(aes(reorder(outcomes,total_outcome), total_outcome)) +
  geom_col(fill = "grey70") +
  geom_text(data = df_positive_outcomes_grouped_sumed %>% filter(total_outcome < 650)
            , aes(label = total_outcome), hjust = -0.1) +
  geom_text(data = df_positive_outcomes_grouped_sumed %>% filter(total_outcome > 650)
            , aes(label = scales::comma(total_outcome), hjust = 1.2)) +
  coord_flip() +
  theme(strip.text.y = element_text(angle = 0, face = "bold")
        , panel.grid.minor.x = element_blank()
        , panel.grid.major.y = element_blank()
        , panel.grid.major = element_line(linetype = 2
                                          , color = "black"
                                          , linewidth = 0.08)
        , axis.text = element_text(size = 10)
        , plot.caption = element_text(size=12
                                      , hjust=1.2, color="black", family = "mono")) +
  facet_grid(Outcome_type~ ., scales = "free_y") +
  labs(x="", y = "number of clients", caption = "Source: Outcomes dataset") +
  scale_y_continuous(expand = c(0,10))
```



## Research Question 1:

```{r data preprocessing for research question 1, cache=TRUE}


# ---- Data Preprocessing for research question 1 ----- #


# ---- removing dependent features from activity/names (1) ---- #

# renaming activity group name (wrongly spelt)
df_activities$nvhActivityGroupName[df$nvhActivityGroupName == "Finanical/Debt"] <- "Financial/Debt"

# removing dependent features in the activity groups
df_activities_2 <- df_activities %>% 
  filter(nvhActivityGroupName != "Outcomes"
         , nvhActivityGroupName != "Sustainment")


# removing dependent features in the activity names
df_activities_3 <- df_activities_2 %>% 
  filter(ActivityName != "Vacancy application - Successful"
         , ActivityName != "Vacancy application - Unsuccessful"
         , ActivityName != "Move to Stage 5")



# ---- creating a new column in outcomes for clients with employment (2) ---- #
df_outcomes_2 <- df_outcomes %>% 
  mutate(Employed = ifelse(`Employment start date` == "NULL"
                           & `Modern Apprenticeship start date` == "NULL"
                           & `Self-employment start date` == "NULL"
                           , 0, 1))




# ---- join both datasets (activities and outcomes) (3) ---- #
df_merged <- df_activities_3 %>% 
  left_join(df_outcomes_2, by = "Unique ID"
            , relationship = "many-to-many")



# remove duplicates since this is a many to many relationship
df_merged_1 <- df_merged %>%
  group_by(ClientActivityID) %>% 
  mutate(flag = row_number()) %>% 
  filter(flag == 1) %>% 
  ungroup()


# ---- exclude all the features except Activity groups and dependent features (4) ---- #
df_merged_2 <- df_merged_1 %>% 
  dplyr::select(nvhActivityGroupName, Employed) %>% 
  na.omit()
```



```{r machine learning model - Logistic regression, cache=TRUE}
# ---- apply machine learning algorithms (5) ---- #

# applying logistic regression
activity_fit <- glm(Employed ~ nvhActivityGroupName, data = df_merged_2, family = "binomial")

# logistic regression model summary
summary(activity_fit)
```



```{r machine learning model - ANOVA, fig.width=8, fig.height=6, warning=FALSE, cache=TRUE}
# perform Anova (test for group differences in activity groups)
anova_fit <- aov(Employed ~ nvhActivityGroupName, data = df_merged_2) 

# check anova summary
summary(anova_fit)


# calculate group means
activity_group_means <- aggregate(df_merged_2$Employed, by = list(df_merged_2$nvhActivityGroupName)
          , FUN = mean)

# rename variable
names(activity_group_means)[1:2] <- c("Activity_group", "group_means")


## plot group means ##
# create a function to plot group means
make_plot <- function(city_deal_df) {
  # create aesthetic
  p1 <- ggplot(city_deal_df
               , aes(reorder(Activity_group,group_means)
                     , group_means))
  
  # add plot type
  p2 <- p1 + geom_col(fill = "grey65") +
    coord_flip() # flip chart (switch x and y axis)
  
  
  # highlight activity over 0.4 group mean (most important activities)
  p3 <- p2 + geom_col(data = activity_group_means %>% 
                        filter(group_means > 0.4), fill = "#FF9999") 
  
  # theme
  p4 <- p3 + theme(panel.grid = element_blank()
                   , panel.grid.major.x = element_line(linetype = 2, linewidth = 0.09)
                   , axis.text = element_text(size = 11)) +
    labs(x= "Activity group", y = "group means")
  
  
  # add text or figures to plot (start with activities with more than 0.4 means)
  p5 <- p4 + geom_text(data = activity_group_means %>% filter(group_means > 0.4)
                       , aes(label = round(group_means,2), hjust = 1.1))
  
  # add text or figures to plot (start with activities with less than 0.4 means)
  p6 <- p5 + geom_text(data = activity_group_means %>% filter(group_means < 0.4)
                       , aes(label = round(group_means,2), hjust = -0.1))
  
  
  # expand scale (to reduce the gap between the y axis and the bars)
  p7 <- p6 + scale_y_continuous(expand = c(0,0.009))
  
  
  p7
}


make_plot(activity_group_means)
```


```{r, ANOVA plot means, fig.width=12, fig.height=8}
# plot anova fit (excluded from final report)
plotmeans(Employed ~ nvhActivityGroupName, data = df_merged_2)
```


```{r machine learning model - Decision trees ensemble, cache=TRUE}
# ---- apply machine learning algorithms ---- #

# To apply decision trees ensemble (bagging and randomForest) -
# - we need to preprocess the data such that each intervention is -
# - considered a feature, hence we will have 17 features

# data processing to apply decision trees ensemble

df_merged_1 %>% 
  dplyr::select(`Unique ID`, nvhActivityGroupName, Employed) %>% 
  group_by(`Unique ID`, nvhActivityGroupName, Employed) %>% 
  summarise(activity_count = n()) %>% 
  ungroup() %>% 
  # each intervention should be a features (using pivot wider)
  pivot_wider(names_from = "nvhActivityGroupName", values_from = "activity_count"
            , values_fill = 0) %>% 
  # remove un-needed columns
  dplyr::select(- `Unique ID`) -> df_decision_trees


# convert the output feature to a factor
df_decision_trees$Employed <- factor(ifelse(df_decision_trees$Employed < 1, "No","Yes"))


# remove observations or rows with missing values
na.omit(df_decision_trees) -> df_decision_trees_2


# some features have spaces inbetween their names, we need to replace it with a dot -
# - for example "make join" will be "make.join"
names(df_decision_trees_2) <- gsub(" ", ".", names(df_decision_trees_2))

# replace features with "/" with "."
names(df_decision_trees_2) <- gsub("/", ".", names(df_decision_trees_2))


# the file below, was created using the steps itemized above (done on excel)
# the file below was created separately but it's done using the same steps as above -
# same as "df_decision_trees_2" file
df2 <- read_excel("Activity_group_df.xlsx")

# renaming entry
rename(df2, c(oldname="Finanical/Debt", oldname="Finanical/Debt"))


# convert the output or dependent varible to a factor and assign to a new variable
Employed_at_any_time <- factor(ifelse(df2$Employed < 1, "No","Yes"))


#create new dataframe
df2 %>% 
  data.frame(Employed_at_any_time) %>% 
  dplyr::select(-Employed) %>% 
  na.omit() -> df3

# perform bagging with 1000 trees 
# Bagging uses all the features to construct each tree
set.seed(1) # set seed so we have the same answer
activity_bagging <- randomForest(Employed_at_any_time ~ ., 
                        data = df3, importance = TRUE, ntree = 1000, mtry = 16)


# MeanDecrese for bagging
MeanDecrease_bagging = importance(activity_bagging, type = 1)


# perform randomForest with 1000 trees 
# RF uses few features (picked at random) for each tree construction
set.seed(1) # set seed so we have the same answer
activity_rf <- randomForest(Employed_at_any_time ~ ., 
                                 data = df3, importance = TRUE, ntree = 1000)

# MeanDecrese for bagging
MeanDecrease_rf = importance(activity_rf, type = 1)
```



```{r merge decision tree ensemble with ANOVA, fig.width=12, fig.height=8}
# create a new dataframe for both bagging and random forest feature importance
df_bagging <- as.data.frame(MeanDecrease_bagging) %>% 
  mutate(Activity_group = c("Client interaction","Contact"
                             ,"Employability development", "Events", "Exit"
                            , "Financial/Debt", "IAG", "Job Related"
                            , "Job search and job matching", "Referrals"
                            , "Registration" , "Specialist Advice" , "Stage"
                            , "Support" , "Training", "Work Experience"
                            ))


df_rf <- as.data.frame(MeanDecrease_rf) %>% 
  mutate(Activity_group = c("Client interaction","Contact"
                            ,"Employability development", "Events", "Exit"
                            , "Financial/Debt", "IAG", "Job Related"
                            , "Job search and job matching", "Referrals"
                            , "Registration" , "Specialist Advice" , "Stage"
                            , "Support" , "Training", "Work Experience"
  ))



# remove rowheaders in both dataframes
rownames(df_bagging) <- NULL
rownames(df_rf) <- NULL

# merge both tables using the common feature name "Activity group
feature_importance_df <- merge(df_bagging, df_rf, by = "Activity_group"
                               , suffixes = c("_Bagging","_RandomForest"))


# merge with the anova table (from the Activity_group_anova, sheet)
anova_bagging_rf_df <- merge(feature_importance_df,
                             activity_group_means, by = "Activity_group") 


# rename columns
colnames(anova_bagging_rf_df) <- c("Activity_group", "Bagging (Mean Decrease Accuracy)"
                                   , "RandomForest (Mean Decrease Accuracy)"
                                   , "ANOVA (Group Means)")


facet_df <- pivot_longer(anova_bagging_rf_df, cols = c("Bagging (Mean Decrease Accuracy)"
                                           , "RandomForest (Mean Decrease Accuracy)"
                                           , "ANOVA (Group Means)"))




# because we needed to sort based on ANOVA (which i have not been able to figure out -, 
# - I will change the Activity group to factors so the plot can be sorted based on ANOVA)
# make the metrics column a factor instead of character
facet_df$Activity_group <- factor(facet_df$Activity_group
                                                , levels = c("Support"
                                                             , "Job search and job matching"
                                                             , "Job Related"
                                                             , "Financial/Debt"
                                                             , "IAG"
                                                             , "Client interaction"
                                                             , "Employability development"
                                                             , "Contact"
                                                             , "Specialist Advice"
                                                             , "Exit"
                                                             , "Referrals"
                                                             , "Stage"
                                                             , "Registration"
                                                             , "Training"
                                                             , "Work Experience"
                                                             , "Events"))






# plot the scores for ANOVA, Bagging and RandomForest

q1 <- ggplot(facet_df, aes(fct_rev(Activity_group), value)) +
  geom_col(fill = "grey65") +
  coord_flip() +
  facet_grid(~name, scales = "free")



q2 <- q1 + geom_col(data = facet_df %>% 
                      filter(Activity_group == "Support" | 
                               Activity_group == "Job Related" |
                               Activity_group == "Job search and job matching")
                    , fill = "#FF9999") 



# -- add text for ANOVA group -- #
q3 <- q2 + 
  # add text for means greater than 0.39 (exclude Financial debt -
  # - it is rounding up to 0.4 when it's actually 0.395)
  geom_text(data = facet_df %>% #add text for means greater than 0.39
              filter(name == "ANOVA (Group Means)") %>%
              filter(value > 0.39),
            aes(label = scales::comma(round(value,2)),hjust = 1)) +
  
  # add text for means less than 0.39
  geom_text(data = facet_df %>% 
              filter(name == "ANOVA (Group Means)") %>%
              filter(value < 0.39 , Activity_group != "Financial/Debt"),
            aes(label = scales::comma(round(value,2)),hjust = -0.05)) +
  
  # add text only for Financial debt, it is rounding up to 0.4 when it's actually 0.395)
  geom_text(data = facet_df %>% 
              filter(name == "ANOVA (Group Means)") %>%
              filter(value < 0.4 , Activity_group == "Financial/Debt"),
            aes(label = round(value,2)),hjust = -0.05)
  


# -- add text for Bagging group -- #
q4 <- q3 + 
  
  # add text for mean decrease score greater than 75 (important features)
  geom_text(data = facet_df %>% 
                      filter(name == "Bagging (Mean Decrease Accuracy)") %>%
                      filter(value > 75),
                    aes(label = scales::comma(round(value,2)),hjust = 1)) +
  
   # add text for values less than 75 mean decrease score
  geom_text(data = facet_df %>%
              filter(name == "Bagging (Mean Decrease Accuracy)") %>%
              filter(value < 75),
            aes(label = scales::comma(round(value,1)),hjust = -0.05))



# -- add text for RandomForest group -- #
q5 <- q4 + 
  
  # add text for values greater than 50 (important features)
  geom_text(data = facet_df %>% 
                       filter(name == "RandomForest (Mean Decrease Accuracy)") %>%
                       filter(value > 50),
                     aes(label = scales::comma(round(value,2)),hjust = 1)) +
  
  # add text for values greater less than 50
  geom_text(data = facet_df %>% 
              filter(name == "RandomForest (Mean Decrease Accuracy)") %>%
              filter(value < 50),
            aes(label = scales::comma(round(value,1)),hjust = -0.05))


# add theme with text
q5 + labs(x = "", y = "scoring metrics") +
  theme(panel.grid = element_blank()
        , panel.grid.major.x = element_line(linetype = 2, linewidth = 0.05)
        , axis.text = element_text(size = 13)
        , strip.text = element_text(size = 10, face = "bold"))
```


```{r feature importance for activity names, fig.width=12, fig.height=8, cache=TRUE}
# -- plot the feature importance for activity names (under activity groups) -- #


# read in dataset
df <- read_excel("Activity_group_name_age_employed_all.xlsx")

# renaming entry
df$nvhActivityGroupName[df$nvhActivityGroupName == "Finanical/Debt"] <- "Financial/Debt"


# remove client(s) that don't exist in both Activity and outcome sheet 
df2 <- df %>% na.omit()


# remove activity group that are dependent on the output (Employed)
df3 <- df2 %>% 
  filter(nvhActivityGroupName != "Outcomes"
         , nvhActivityGroupName != "Sustainment")



# remove activity names that are dependent on the output (Employed)
df4 <- df3 %>% 
  filter(ActivityName != "Vacancy application - Successful"
         , ActivityName != "Vacancy application - Unsuccessful"
         , ActivityName != "Move to Stage 5")



# make df wider such that activity names will be features
df5 <- df4 %>% dplyr::select(ClientRef, ActivityName, Employed) %>% 
  group_by(ClientRef,Employed,ActivityName) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = ActivityName, values_from = count, values_fill = 0) %>% 
  as_tibble()

# convert the output or dependent varible to a factor and assign to a new variable
Employed_at_any_time <- factor(ifelse(df5$Employed < 1, "No","Yes"))


#create new dataframe
df5 %>% 
  data.frame(Employed_at_any_time) %>% 
  dplyr::select(-Employed, -ClientRef) %>% 
  na.omit() -> df6



#perform random forest with 500 trees
set.seed(1)
activity_name_rf <- randomForest(Employed_at_any_time ~ ., 
                            data = df6, importance = TRUE, ntree = 500)

varImpPlot(activity_name_rf)

# MeanDecrese for rf
MeanDecrease_activity_name_rf = importance(activity_name_rf, type = 1)


## create a new dataframe for random forest feature importance ##


# for random forest
activity_name_rf_df <- as.data.frame(MeanDecrease_activity_name_rf) %>%
  
  # using the gsub to remove the fullstop in the activity names
  mutate(Activity_name = gsub("\\."," ",rownames(MeanDecrease_activity_name_rf))) 


# remove rowheaders in both dataframes
rownames(activity_name_rf_df) <- NULL
```

```{r, fig.width=12, fig.height=6}
# -- create a facet plot of only important interventions (or activity groups) -- #


df4 %>% 
  dplyr::select(nvhActivityGroupName, ActivityName) %>% 
  group_by(nvhActivityGroupName, ActivityName) %>% 
  summarise(count = n()) %>% 
  dplyr::select(-count) -> df_activity_groups_and_names



# -- Merging and plot for Random Forest -- #
df_name <- pivot_longer(df5, cols = -ClientRef)


# before we merge, we need to ensure the activity names will match with the second table
activity_name_rf_df[activity_name_rf_df$Activity_name == "In work Support Provided"
                    ,"Activity_name"] <- "In-work Support Provided"



# merging the RandomF feature importance dataframe and df_activity_groups_and_names
df6_activity_name_random_forest <- merge(df_activity_groups_and_names
                                         , activity_name_rf_df
                                         , by.x = "ActivityName"
                                         , by.y = "Activity_name")



# filtering for important interventions
df7_activity_name_random_forest <- df6_activity_name_random_forest %>% 
  filter(nvhActivityGroupName == "Support"
         | nvhActivityGroupName == "Job Related"
         | nvhActivityGroupName == "Job search and job matching")




# making the facet plot for RandomForest model

# create plot canvas
t1 <- ggplot(df7_activity_name_random_forest
             , aes(reorder(ActivityName,MeanDecreaseAccuracy)
                   , MeanDecreaseAccuracy))

# add plot type to canvas
t2 <- t1 + geom_col(fill = "grey65") 

# flip the plot so that x axis will rotate (become y axis, and vice-versa)
t3 <- t2 + coord_flip() 

# add the facet grid
t4 <- t3 + facet_grid(nvhActivityGroupName~., scales = "free") 


# add the figures of each activity
t5 <- t4 + 
  geom_text(aes(label = round(MeanDecreaseAccuracy,1)), hjust = -0.1)

# adjust the theme of the plot
t6 <- t5 + theme(panel.grid = element_blank()
                 , panel.grid.major.x = element_line(linetype = 2, linewidth = 0.05)
                 , axis.text = element_text(size = 13)
                 , strip.text = element_text(size = 10, face = "bold")
                 , strip.text.y = element_text(angle = 0)) 

# discard the x-axis label
t7 <- t6 + labs(x=""
                , y = "Feature Importance")

t7
```




## Research Question 2:


```{r time duration by contract type, fig.width=8, fig.height=6, cache=TRUE}


# ---- data processing for time duration by contract type ---- #

# read in dataset (for data cleaning purposes, I created a new file on excel, this file is a combination of the Outcomes and Activities datasets. The dataset had to be cleaned on excel, in a way, it is better done on excel than using R or python)
df <- read_excel("Unique_Data_Activities_Employed_1.xlsx")


# View Top 5 rows
head(df, 5)


# -- get the average total hours by contract type -- #


# group by contract type
df_group_by_contract_type <- df %>% group_by(`Contract type`) %>% 
  summarise(average_beneficiary_hours = mean(BeneficiaryHours)
            , number_of_clients = n_distinct(ClientRef))



# pivot longer for facet plot purposes
df_group_by_contract_type_2 <- pivot_longer(
  df_group_by_contract_type
  , cols = c("average_beneficiary_hours"
             ,"number_of_clients")
  , names_to = "metrics")


# make the metrics column a factor instead of character
df_group_by_contract_type_2$metrics <- factor(
  df_group_by_contract_type_2$metrics
  , levels = c("number_of_clients"
               , "average_beneficiary_hours"))


# exclude unemployment since it is not a contract type
df_group_by_contract_type_3 <- df_group_by_contract_type_2 %>% 
  filter(`Contract type` != "Unemployed")


# visualize the data frame (facet plot)
# this function was created earlier (check time duration codes)
make_facet_plot(df_group_by_contract_type_3
                ,`Contract type`
                , value, metrics) +
  
  
# highlighting average hours for permanent contract type
geom_col(data = df_group_by_contract_type_3 %>% 
           filter(`Contract type` == "Permanent"
                  , value > 1 
                  , metrics == "average_beneficiary_hours")
         , aes(fill = "#FF9999")) +
  
  # ---- add text or values in the number_of_clients plot ---- #
  
  # adding text to the plot for only the contact type bar in the count_of_activities_plot
  geom_text(data =df_group_by_contract_type_3 %>% 
              filter(`Contract type` == "Permanent" 
                     , metrics == "number_of_clients")
            , aes(label = scales::comma(value), hjust = 1.1)) +

  # adding text to the plot for other contract type in the number_of_clients plot
  geom_text(data =df_group_by_contract_type_3 %>% 
              filter(`Contract type` != "Permanent" 
                     , metrics == "number_of_clients")
            , aes(label = scales::comma(value), hjust = -0.1)) +
  
  # ---- add text or values in the average beneficiaries hours plot ---- #
  
  # adding text to the plot for high value activities (values inside the bar)
  geom_text(data =df_group_by_contract_type_3 %>% 
              filter(`Contract type` == "Permanent"
                     , metrics == "average_beneficiary_hours")
            , aes(label = round(value,2), hjust = 1.1)) +
  
  # adding text to the plot for low value activity group (values outside the bar)
  geom_text(data =df_group_by_contract_type_3 %>% 
              filter(`Contract type` != "Permanent"
                     , metrics == "average_beneficiary_hours")
            , aes(label = round(value,2), hjust = -0.1)) +
  theme(legend.position = "none") +
  labs(x = "Contract type", y = "")

```




```{r Age Cohort by activities count and average activities, fig.width=8, fig.height=6, cache=TRUE}

# ---- data processing for Age cohorts (Young and Old clinets) ---- #

# 3.1 select specific activities (ClientRef, Activity group name, ClientActivityID) columns
df2_activities <- df_activities %>% 
  dplyr::select(1, 3, 8)


# renaming entry
df2_activities$nvhActivityGroupName[
  df2_activities$nvhActivityGroupName == "Finanical/Debt"] <- "Financial/Debt"



# Convert nvhActivityGroupName from character to factors data type
df2_activities$nvhActivityGroupName <- factor(
  df2_activities$nvhActivityGroupName
  , levels = c("Registration", "Contact"
               , "Stage", "Client interaction", "Financial/Debt"
               , "IAG","Events", "Employability development"
               ,"Support", "Referrals"
               , "Training", "Specialist Advice"
               ,"Job Related", "Job search and job matching"
               ,"Work Experience","Outcomes"
               ,"Sustainment", "Exit"))



# -- 2.2 select unique activities using ActivityID as the indicator -- #
df_unique_activities <- df2_activities %>% 
  group_by(ClientActivityID) %>% 
  
  # assign to a number to each occurrence of clientactivityID
  mutate(flag = row_number()) %>% 
  
  # filter for the first occurrence only (removes duplicates)
  filter(flag == 1) %>% 
  
  # remove the flag column (not needed)
  dplyr::select(-4) 
  
  


# -- 3.1 select only Unique ID, Age and sex in the demographic data -- #
df_demo_age_sex_id <- df_demographic %>% 
  dplyr::select(3,12,13)




# -- 3.2 select only unique clients -- #
df_age_sex_unique <- df_demo_age_sex_id %>% 
  
  # create a new column Age_cohort that assigned clients as either Young or Adult
  mutate(Age_cohort = case_when(
   Age <= 26 ~ "Young"
   , Age > 26 ~ "Adult"
   , TRUE ~ "Age (Unknown)")) %>%  
  
  
  group_by(`Unique ID`) %>% 
  
  # assign to a number to each occurrence of Unique ID
  mutate(flag = row_number()) %>% 
  
  # filter for the first occurrence only (removes duplicates)
  filter(flag == 1) %>%
  
  # remove the flag column from the dataframe
  dplyr::select(-5) 




# -- 
df_age_cohort_count <- df_age_sex_unique %>% 
  group_by(Age_cohort) %>% 
  summarise(total_clients = n())


# -- 5.1 merge the demographic data with the activities data -- #
df_demographic_activity <- df_age_sex_unique %>% 
  left_join(df_unique_activities, by = "Unique ID"
            , relationship = "many-to-many")


  
# -- 5.2 since the merged dataset is a many-to-many relationship, we have duplicates -- #
df_demo_activity_2 <- df_demographic_activity %>% 
  group_by(ClientActivityID) %>% 
  
  # assign a number to each occurrence using clientActivity ID
  mutate(instances = row_number()) %>% 
  
  # removing duplicates by picking only the first instance
  filter(instances == 1) 
 

# -- 6.1 total number of activities by Age cohort  -- #
# (this will be combined with the variable in - 4 - to create a plot)
df_total_activities_age_cohort <- df_demo_activity_2 %>% 
  group_by(Age_cohort) %>% 
  summarise(total_activities = n())



# -- 6.2 merge Code 6 and Code 4 -- #
df_total_activities_total_clients <- df_total_activities_age_cohort %>% 
  left_join(df_age_cohort_count
            , by = "Age_cohort") %>% 
  
  # create a new column that calculates the average activities
  mutate(average_activities = round(total_activities/total_clients,0)) 


# -- 6.3 make the dataframe shorter (inshort make it longer, reduce columns) -- #
df_total_activities_total_clients_2 <- df_total_activities_total_clients %>% 
  
  # pivot longer the plot for facet plot
  pivot_longer(cols = c(-1)) 



# -- 6.4 recode the name column from character to a factor -- #
df_total_activities_total_clients_2$name <-  factor(
  df_total_activities_total_clients_2$name
  , levels = c("total_clients"
               , "total_activities"
               , "average_activities"))

# -- creating facet plot -- #


# set-up facet theme_plot
theme_facet <- theme(panel.grid = element_blank()
      , panel.grid.major.x = element_line(linetype = 2, linewidth = 0.09)
      , axis.text = element_text(size = 11)
      , strip.text = element_text(size = 10, face = "bold"))



#  create plot canvas 
w1 <- df_total_activities_total_clients_2 %>%  
  ggplot(aes(Age_cohort, value))



# Add plot type , should be a bar chart or column chart 
w2 <- w1 + geom_col(fill = "grey80") + coord_flip()


# Add facet, text and theme 
w3 <- w2 + 
  facet_wrap(.~name, scales = "free_x") +
  geom_text(aes(label = scales::comma(value)), hjust = 1.1) +
  theme_facet +
  labs(x = "", y = "")


# View plot
w3
```





```{r Age cohort by Activity groups, fig.width=12, fig.height=8, cache=TRUE}
# we are interested in the number of unique activities performed by each client -. 
# - Such that if a client performs the same activity 4 times -
# - , we say that client performed that activity at least once. - 
# - Here we use the row_number again to count only the first instance
df_performed_at_least_once <- df_demo_activity_2 %>% 
  group_by(`Unique ID`, nvhActivityGroupName) %>%
  
  # assign to a number to each occurrence of Unique ID and nvhActivityGroupName
  mutate(flag = row_number()) %>% 
  
  # filter for first occurrence
  filter(flag == 1) %>% 
  
  group_by(Age_cohort, nvhActivityGroupName) %>% 
  
  # calculate % share
  summarise(performed_act_at_least_once = n()) %>% 
  mutate(share = case_when(
    Age_cohort == "Adult" ~ round(performed_act_at_least_once/2018,2)
    , TRUE ~ round(performed_act_at_least_once/2186,2))) %>% 
  ungroup()


# create a new column that combines the actual value and the percentage
df_performed_at_least_once <- df_performed_at_least_once %>% 
  mutate(value_share_1 = paste0(share*100,"% (",performed_act_at_least_once,")")
         , value_share_2 = paste0(share*100,"% (",performed_act_at_least_once,")"))

# create plot 

p1 <- df_performed_at_least_once %>% 
  ggplot(aes(fct_rev(nvhActivityGroupName)
             , share, fill = Age_cohort))

# add plot type and rotate bars
p2 <- p1 + geom_col(position = "dodge") + 
  coord_flip()

# add text to plot (text for Adult only + less than 0.9 - text will be beside the bars)
p3 <- p2 + geom_text(data = df_performed_at_least_once %>% 
                     filter(Age_cohort == "Adult" 
                            , share < 0.9)
                     , aes(label = value_share_2)
               , hjust = -0.08, vjust = 1.5, size = 3.5)

# add text to plot (text for Adult only + greater than 0.9 - text will be inside the bars)
p4 <- p3 + geom_text(data = df_performed_at_least_once %>% 
                       filter(Age_cohort == "Adult" 
                              , share > 0.9) , aes(label = value_share_2)
                     , hjust = 1.05 , vjust = 1.5, size = 3.5)


# add text to plot (text for Young only + less than 0.9 - text will be beside the bars)
p5 <- p4 + geom_text(data = df_performed_at_least_once %>% 
                       filter(Age_cohort == "Young"
                              , share < 0.9)
                     , aes(label = value_share_2)
                     , hjust = -0.08
                     , vjust = -0.5
                     , size = 3.5)


# add text to plot (text for Young only + less than 0.9 - text will be beside the bars)
p6 <- p5 + geom_text(data = df_performed_at_least_once %>% 
                       filter(Age_cohort == "Young"
                              , share > 0.9), aes(label = value_share_2)
                     , hjust = 1.05 , vjust = -0.5, size = 3.5)


# change scale to a percentage scale and adjust the plot background
p7 <- p6 + scale_y_continuous(labels = scales::percent
                              , expand = c(0,0.01)) + 
  theme(panel.grid.major.y = element_blank()
                 , panel.grid.minor.x = element_blank()
                 , panel.grid.major.x = element_line(linetype = 2
                                                     , linewidth = 0.2
                                                     , color = "grey")
                 , legend.position = "right"
        , legend.title = element_blank()
        , axis.text = element_text(size = 11))


# switch the legend, let Young come before Adult
p8 <- p7 + guides(fill = guide_legend(reverse = TRUE)) +
  labs(x= "",  y= "performed activity at least once")

# display plot
p8
```







```{r outcomes by age group data preprocessing, cache=TRUE}
# -- data preprocessing for outcomes by age cohort -- #


# merge df_outcomes_grouped and demographic data
df_outcomes_grouped_by_age <- df_positive_outcomes_grouped %>% 
  left_join(df_age_sex_unique, by = "Unique ID"
            , relationship = "many-to-many")


# preprocessing data by removing missing values and summarizing data
df_outcomes_grouped_by_age_2 <- df_outcomes_grouped_by_age %>% 
  
  # remove clients without demographic information
  na.omit() %>% 
  
  # 
  group_by(Age_cohort,Outcome_type, outcomes) %>% 
  
  summarise(total_count = sum(value)) %>% 
  
  # this calculates the percentage share of clients for each outcome
  mutate(share = case_when(Age_cohort == "Adult" ~ round(total_count/2018,2) 
                           , TRUE ~ round(total_count/2186,2)))



# creating a new column that combines the actual value and the percentage
df_outcomes_grouped_by_age_3 <- df_outcomes_grouped_by_age_2 %>% 
  
  # create a new column that combines the actual value and the percentage
  mutate(value_share = paste0(share*100,"% (",total_count,")"))
  


# change the Age variable from character to a factor variable
df_outcomes_grouped_by_age_3$Age_cohort <- factor(df_outcomes_grouped_by_age_3$Age_cohort
                                                  , levels = c("Young","Adult"))
  
```



```{r outcomes by age group plot, fig.width=12, fig.height=8, cache=TRUE}
# -- creating plot -- #
ggplot(data = df_outcomes_grouped_by_age_3
       , aes(reorder(outcomes,share), share)) +
  geom_col(fill = "grey70") +
  geom_col(data = df_outcomes_grouped_by_age_3 %>% 
             filter(total_count > 300) , aes(fill = "#FF9999")) +
  geom_text(data = df_outcomes_grouped_by_age_3 %>% filter(share < 0.15), 
            aes(label = value_share),hjust = -0.1) +
  geom_text(data = df_outcomes_grouped_by_age_3 %>% filter(share > 0.13), 
            aes(label = value_share),hjust = 1.1) +
  coord_flip() +
  facet_grid(Outcome_type ~ Age_cohort, scales = "free_y") +
  theme(strip.text.y = element_text(angle = 0, size = 11)
        , strip.text.x = element_text(size = 11)
        , panel.grid.major.y = element_blank()
        , panel.grid.minor.x = element_blank()
        , panel.grid.major.x = element_line(linetype = 2, linewidth = 0.2, color = "grey")
        , legend.position = "none"
        , legend.title = element_blank()
        , axis.text = element_text(size = 11)) +
  labs(y="", x = "Outcomes") +
  scale_y_continuous(labels = scales::percent)
```















